spring:
  application:
    name: Personality Test
  jpa:
    properties:
      hibernate:
        default_schema: public
        dialect: ${DB_DIALECT:org.hibernate.dialect.H2Dialect}
    hibernate:
      ddl-auto: update
      show-sql: true
  datasource:
    url: ${DB_URL:jdbc:h2:mem:mydb}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:password}
    initialization-mode: always
    initialize: true
    continue-on-error: false
  jackson:
    serialization:
      fail-on-empty-beans: false
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true

  output:
    ansi:
      enabled: ALWAYS

server:
  port: 8080

logging:
  level:
    org:
      springframework: DEBUG
      hibernate: ERROR

springdoc:
  swagger-ui:
    path: /swagger-ui.html